// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShassiWPFApp.Persistence;

#nullable disable

namespace ShassiWPFApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240825182918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShassiWPFApp.Entities.HarnessDrawing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Drawing")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Drawing");

                    b.Property<string>("DrawingVersion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Drawing_version");

                    b.Property<string>("Harness")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Harness");

                    b.Property<string>("HarnessVersion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Harness_version");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Harness_drawing_ID");

                    b.ToTable("Harness_drawing", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 40953,
                            Drawing = "EP",
                            DrawingVersion = "S-4",
                            Harness = "S2563532M",
                            HarnessVersion = "S-6"
                        },
                        new
                        {
                            Id = 40442,
                            Drawing = "EP",
                            DrawingVersion = "S-4",
                            Harness = "S2563545M",
                            HarnessVersion = "S12"
                        },
                        new
                        {
                            Id = 39087,
                            Drawing = "EP",
                            DrawingVersion = "S-4",
                            Harness = "S2563549M",
                            HarnessVersion = "S-9"
                        },
                        new
                        {
                            Id = 39077,
                            Drawing = "EP",
                            DrawingVersion = "S-4",
                            Harness = "S2641137M",
                            HarnessVersion = "S-9"
                        },
                        new
                        {
                            Id = 38643,
                            Drawing = "EP",
                            DrawingVersion = "S-4",
                            Harness = "S2656843M",
                            HarnessVersion = "5"
                        });
                });

            modelBuilder.Entity("ShassiWPFApp.Entities.HarnessWire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Color");

                    b.Property<int>("HarnessID")
                        .HasColumnType("integer")
                        .HasColumnName("Harness_ID");

                    b.Property<string>("Housing1")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Housing_1");

                    b.Property<string>("Housing2")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Housing_2");

                    b.Property<string>("Length")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Length");

                    b.HasKey("Id");

                    b.HasIndex("HarnessID");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Harness_wires_ID");

                    b.ToTable("Harness_wires", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3115654,
                            Color = "R",
                            HarnessID = 38643,
                            Housing1 = "C604:19",
                            Housing2 = "P2.BX2:1",
                            Length = "950"
                        },
                        new
                        {
                            Id = 3115655,
                            Color = "R",
                            HarnessID = 38643,
                            Housing1 = "C604:23",
                            Housing2 = "C521:1",
                            Length = "450"
                        },
                        new
                        {
                            Id = 3158749,
                            Color = "BN",
                            HarnessID = 39077,
                            Housing1 = "E71.B:1",
                            Housing2 = "C604:21",
                            Length = "665"
                        },
                        new
                        {
                            Id = 3158750,
                            Color = "GR",
                            HarnessID = 39077,
                            Housing1 = "E71.B:4",
                            Housing2 = "C604:23",
                            Length = "665"
                        },
                        new
                        {
                            Id = 3159894,
                            Color = "W",
                            HarnessID = 39087,
                            Housing1 = "E71.A:1",
                            Housing2 = "C681",
                            Length = "465"
                        },
                        new
                        {
                            Id = 3159895,
                            Color = "SB",
                            HarnessID = 39087,
                            Housing1 = "E71.P:3",
                            Housing2 = "G504-2",
                            Length = "680"
                        },
                        new
                        {
                            Id = 3277678,
                            Color = "GN",
                            HarnessID = 40442,
                            Housing1 = "P2.E85:1",
                            Housing2 = "C680",
                            Length = "475"
                        },
                        new
                        {
                            Id = 3277679,
                            Color = "R",
                            HarnessID = 40442,
                            Housing1 = "P2.BX2:1",
                            Housing2 = "E30.P:1",
                            Length = "980"
                        },
                        new
                        {
                            Id = 3328453,
                            Color = "W",
                            HarnessID = 40953,
                            Housing1 = "C621:6",
                            Housing2 = "C681",
                            Length = "365"
                        },
                        new
                        {
                            Id = 3328454,
                            Color = "SB",
                            HarnessID = 40953,
                            Housing1 = "C620:24",
                            Housing2 = "G508-3",
                            Length = "305"
                        });
                });

            modelBuilder.Entity("ShassiWPFApp.Entities.HarnessWire", b =>
                {
                    b.HasOne("ShassiWPFApp.Entities.HarnessDrawing", "HarnessDrawing")
                        .WithMany("HarnessWires")
                        .HasForeignKey("HarnessID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HarnessDrawing");
                });

            modelBuilder.Entity("ShassiWPFApp.Entities.HarnessDrawing", b =>
                {
                    b.Navigation("HarnessWires");
                });
#pragma warning restore 612, 618
        }
    }
}
